# Generated by Django 3.2 on 2022-07-28 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created', 'updated'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
    ]
